-- ─────────────────────────────────────────────────────────────────────────────
-- Business Hub — admin task-management + submission-review tables
-- Run ONCE in Supabase → SQL Editor (New query → paste → Run).
-- Safe to re-run: uses "create table if not exists".
-- ─────────────────────────────────────────────────────────────────────────────

-- Tasks created/managed from the admin panel (shown on the dashboard alongside
-- the built-in starter tasks).
create table if not exists tasks (
  id           text primary key,
  title        text not null,
  description  text default '',
  category     text default 'General',
  poster       text default 'Business Hub',
  location     text default 'Remote',
  questions    jsonb default '[]'::jsonb,
  payment      numeric default 0,        -- reward paid on approval
  slots        integer default 0,        -- limit: max workers (0 = unlimited)
  claimed      integer default 0,        -- incremented when a submission is approved
  active       boolean default true,     -- off = hidden from the dashboard
  created_at   timestamptz default now()
);

-- Completed-work submissions awaiting admin approve/reject.
create table if not exists submissions (
  id           bigint generated by default as identity primary key,
  user_id      text,
  user_email   text,
  user_name    text,
  task_id      text,
  task_title   text,
  reward       numeric default 0,
  note         text default '',
  status       text default 'pending',   -- pending | approved | rejected
  created_at   timestamptz default now(),
  updated_at   timestamptz
);

create index if not exists submissions_status_idx on submissions (status);
create index if not exists tasks_active_idx        on tasks (active);
