-- ─────────────────────────────────────────────────────────────────────────────
-- Business Hub — admin task-management + submission-review tables
-- Run ONCE in Supabase → SQL Editor (New query → paste → Run).
-- Safe to re-run: uses "create table if not exists".
-- ─────────────────────────────────────────────────────────────────────────────

-- Tasks created/managed from the admin panel (shown on the dashboard alongside
-- the built-in starter tasks).
create table if not exists tasks (
  id           text primary key,
  title        text not null,
  description  text default '',
  category     text default 'General',
  poster       text default 'Business Hub',
  location     text default 'Remote',
  questions    jsonb default '[]'::jsonb,
  payment      numeric default 0,        -- reward paid on approval
  slots        integer default 0,        -- limit: max workers (0 = unlimited)
  claimed      integer default 0,        -- incremented when a submission is approved
  active       boolean default true,     -- off = hidden from the dashboard
  created_at   timestamptz default now()
);

-- Completed-work submissions awaiting admin approve/reject.
create table if not exists submissions (
  id           bigint generated by default as identity primary key,
  user_id      text,
  user_email   text,
  user_name    text,
  task_id      text,
  task_title   text,
  reward       numeric default 0,
  note         text default '',
  status       text default 'pending',   -- pending | approved | rejected
  created_at   timestamptz default now(),
  updated_at   timestamptz
);

create index if not exists submissions_status_idx on submissions (status);
create index if not exists tasks_active_idx        on tasks (active);

-- Rejection reason for withdrawals (added to the existing withdrawal_requests table)
alter table withdrawal_requests add column if not exists reject_reason text;

-- Correction reason for completed-work submissions + a 'correction' status option.
alter table submissions add column if not exists reason text default '';

-- ─────────────────────────────────────────────────────────────────────────────
-- Task Applications (proposals). A user must submit a proposal and have it
-- approved before they can begin/submit a task. Shown in the admin panel's
-- "Task Applications" module.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists applications (
  id           bigint generated by default as identity primary key,
  user_id      text,
  user_email   text,
  user_name    text,
  task_id      text,
  task_title   text,
  message      text default '',          -- cover letter / why they are suitable
  extra        text default '',          -- optional additional information
  status       text default 'pending',   -- pending | approved | rejected | correction
  reason       text default '',          -- rejection / correction reason
  created_at   timestamptz default now(),
  updated_at   timestamptz
);
create index if not exists applications_status_idx on applications (status);
create index if not exists applications_user_idx   on applications (user_id);
create index if not exists applications_task_idx   on applications (task_id);

-- Audit trail of admin actions (approvals, rejections, correction emails, …).
create table if not exists admin_actions (
  id          bigint generated by default as identity primary key,
  action      text,                      -- e.g. approve_application, request_correction
  entity      text,                      -- application | submission
  entity_id   text,
  detail      text default '',
  actor       text default 'admin',
  created_at  timestamptz default now()
);
create index if not exists admin_actions_created_idx on admin_actions (created_at desc);

-- Email opt-out. When true, the user has unsubscribed from all account emails.
alter table users add column if not exists unsubscribed boolean default false;

-- ─────────────────────────────────────────────────────────────────────────────
-- Performance indexes on high-traffic / frequently-queried columns.
-- Safe to re-run.
-- ─────────────────────────────────────────────────────────────────────────────
create index if not exists users_email_idx            on users (lower(email));
create index if not exists users_referred_by_idx       on users (referred_by);
create index if not exists submissions_user_idx        on submissions (user_id);
create index if not exists submissions_created_idx      on submissions (created_at desc);
create index if not exists withdrawals_user_idx         on withdrawal_requests (user_id);
create index if not exists withdrawals_status_idx       on withdrawal_requests (status);
create index if not exists tasks_created_idx            on tasks (created_at desc);

-- ─────────────────────────────────────────────────────────────────────────────
-- Rate limiting (fixed-window counters for login/register). Fails open in code,
-- so this is optional but recommended for brute-force protection.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists rate_limits (
  bucket       text primary key,
  count        integer not null default 0,
  window_start timestamptz not null default now()
);

-- ─────────────────────────────────────────────────────────────────────────────
-- Global key/value app settings, editable from the admin panel (e.g. the M-Pesa
-- Buy Goods till number used for Premium + withdrawal-fee payments). Optional:
-- the code falls back to a baked-in default till (1545320) if this is absent.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists app_settings (
  key        text primary key,
  value      text default '',
  updated_at timestamptz default now()
);
insert into app_settings (key, value) values ('mpesa_till', '1545320')
  on conflict (key) do nothing;
