-- ─────────────────────────────────────────────────────────────────────────────
-- M-PESA (Daraja) transactions — tracks STK Push (incoming) and B2C (outgoing)
-- for verification, idempotency and audit. Run ONCE in Supabase → SQL Editor.
-- Safe to re-run.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists mpesa_transactions (
  id                          bigint generated by default as identity primary key,
  direction                   text default 'stk',    -- stk | b2c
  purpose                     text,                  -- activation | premium | withdrawal_fee | withdrawal_payout | credit
  status                      text default 'pending',-- pending | success | failed | timeout
  amount                      numeric default 0,
  phone                       text,
  user_id                     text,
  withdrawal_id               text,                  -- links a B2C payout to its withdrawal_requests row
  checkout_request_id         text,                  -- STK
  merchant_request_id         text,                  -- STK
  conversation_id             text,                  -- B2C
  originator_conversation_id  text,                  -- B2C
  mpesa_receipt               text,
  result_code                 text,
  result_desc                 text,
  created_at                  timestamptz default now(),
  updated_at                  timestamptz
);

create unique index if not exists mpesa_tx_checkout_idx on mpesa_transactions (checkout_request_id);
create index if not exists mpesa_tx_conv_idx      on mpesa_transactions (conversation_id);
create index if not exists mpesa_tx_user_idx      on mpesa_transactions (user_id);
create index if not exists mpesa_tx_status_idx    on mpesa_transactions (status);
create index if not exists mpesa_tx_withdrawal_idx on mpesa_transactions (withdrawal_id);

-- withdrawal_requests gains 'processing' and 'paid' statuses (no schema change
-- needed — the status column is free text).
