-- ─────────────────────────────────────────────────────────────────────────────
-- Unified payment ledger — records every payment (Daraja / Paystack / M-Pesa
-- Till) with the fields needed for admin audit + idempotent verification.
-- Daraja STK/B2C already have their own detailed table (mpesa_transactions);
-- the admin Transactions view merges both. Run ONCE in Supabase → SQL Editor.
-- Safe to re-run.
-- ─────────────────────────────────────────────────────────────────────────────
create table if not exists payment_events (
  id            bigint generated by default as identity primary key,
  user_id       text,
  type          text,                     -- registration | premium | withdrawal_fee | training | other
  amount        numeric default 0,
  currency      text default 'KES',
  provider      text,                     -- daraja | paystack | mpesa_till
  reference     text,                     -- provider transaction / reference id (idempotency key)
  phone         text,
  email         text,
  status        text default 'pending',   -- pending | successful | failed | cancelled | reversed
  verify_status text default 'unverified',-- unverified | verified | mismatch
  withdrawal_id text,                      -- links a consumed withdrawal-fee payment to its request (single-use)
  created_at    timestamptz default now(),
  updated_at    timestamptz
);

-- If the table already existed, make sure the consumption column is present.
alter table payment_events add column if not exists withdrawal_id text;

-- Idempotency: one row per (provider, reference) when a reference is present.
create unique index if not exists payment_events_ref_idx
  on payment_events (provider, reference) where reference is not null;
create index if not exists payment_events_user_idx     on payment_events (user_id);
create index if not exists payment_events_status_idx   on payment_events (status);
create index if not exists payment_events_provider_idx on payment_events (provider);
create index if not exists payment_events_type_idx     on payment_events (type);
create index if not exists payment_events_created_idx  on payment_events (created_at desc);
